## PA, PF, PD - tested with helm chart 0.4.1

global:
  image:
    tag: "edge"
  ingress:
    enabled: true
    addReleaseNameToHost: prepend
    defaultDomain: ping-devops.com
    defaultTlsSecret:
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      kubernetes.io/ingress.class: "nginx-public"

pingaccess-admin:
  enabled: true
  privateCert:
    generate: true
  envs:
    SERVER_PROFILE_BASELINE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
    SERVER_PROFILE_BASELINE_PATH: baseline/pingaccess
    SERVER_PROFILE_PARENT: BASELINE
    SERVER_PROFILE_URL: https://github.com/samir-gandhi/server-profiles
    SERVER_PROFILE_PATH: splunk-logs/pingaccess
    TAIL_LOG_FILES: "/opt/out/instance/log/pingaccess.log /opt/out/instance/log/pingaccess_engine_audit_splunk.log /opt/out/instance/log/pingaccess_api_audit_splunk.log /opt/out/instance/log/pingaccess_agent_audit_splunk.log"
  container:
    waitFor:
      pingfederate-engine:
        service: https

pingaccess-engine:
  enabled: true
  envs:
    SERVER_PROFILE_BASELINE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
    SERVER_PROFILE_BASELINE_PATH: baseline/pingaccess
    SERVER_PROFILE_PARENT: BASELINE
    SERVER_PROFILE_URL: https://github.com/samir-gandhi/server-profiles
    SERVER_PROFILE_PATH: splunk-logs/pingaccess
    TAIL_LOG_FILES: "/opt/out/instance/log/pingaccess.log /opt/out/instance/log/pingaccess_engine_audit_splunk.log /opt/out/instance/log/pingaccess_api_audit_splunk.log /opt/out/instance/log/pingaccess_agent_audit_splunk.log"
pingdataconsole:
  enabled: true

pingdirectory:
  container:
    replicaCount: 1
  enabled: true

pingfederate-admin:
  enabled: true
  envs:
    SERVER_PROFILE_BASELINE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
    SERVER_PROFILE_BASELINE_PATH: baseline/pingfederate
    SERVER_PROFILE_PARENT: BASELINE
    SERVER_PROFILE_URL: https://github.com/samir-gandhi/server-profiles
    SERVER_PROFILE_PATH: splunk-logs/pingfederate
    TAIL_LOG_FILES: "/opt/logs/server.log /opt/logs/splunk-audit.log"


pingfederate-engine:
  enabled: true
  envs:
    SERVER_PROFILE_BASELINE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
    SERVER_PROFILE_BASELINE_PATH: baseline/pingfederate
    SERVER_PROFILE_PARENT: BASELINE
    SERVER_PROFILE_URL: https://github.com/samir-gandhi/server-profiles
    SERVER_PROFILE_PATH: splunk-logs/pingfederate
    TAIL_LOG_FILES: "/opt/logs/server.log /opt/logs/splunk-audit.log"