# This YAML file is used for QA, staging, and prod containers.
# The image definition's tag should be changed according to environment. See
# .env file's REACT_APP_HOST var for reason for environment specfic images.
# The Dev environment has its own DockerFile and Compose YAML file because we want 
# a React dev build that allows for hot code reloading and volume mounted source for
# development with VSCode Remote.
 
version: '3.3'
services:
    BXFinance:
        ports:
            - '5000:5000'
        image: 'bxfinanceapp:latest' # Tag options are qa, stage, prod.